### ISSUE TITLE
Compile time validation of all passed options

### ISSUE THREAD

**Issue by i1t** [sorentwo/oban#55]
It doesn't resolve the real value of `max_attempts` option. Can't even do the following:

```
@max_attempts 1
use Oban.Worker, queue: "background", max_attempts: @max_attempts
```

since it results in

```
{:@, [line: 17], [{:max_attempts, [line: 17], nil}]}

== Compilation error in file lib/pleroma/workers/background_worker.ex ==
** (ArgumentError) expected :max_attempts to be an integer greater than 0
```

This feature limitation seems unnecesary. Please make it optional.

**Comment by sorentwo** [comment]
Is there a reason you would specify the value as a module attribute? They are both compile time constants, it doesn’t buy you any dynamism.

If you need a dynamic value for max_attempts you can always pass it in at runtime, when the job is enqueued.

**Comment by i1t** [comment]
@sorentwo 

It's just a trivial example of how limiting this new approach is. In real-life scenarios we use `Application.get_env/3` to obtain compile time setting. This is working in 0.6.0 but upgrading to 0.7.1 broke that.

**Comment by sorentwo** [comment]
Ok, using `Application.get_env` makes more sense. I'm thinking through reverting those changes. In the meantime you can work around it by overriding `new/2` within your worker:

```elixir
def new(args, opts \\ []) when is_map(args) and is_list(opts) do
  opts =
    @opts
    |> Keyword.merge(Application.get_env(:app, :thing, 1))
    |> Keyword.merge(opts)

  Job.new(args, opts)
end
```

**Comment by i1t** [comment]
> Ok, using `Application.get_env` makes more sense. I'm thinking through reverting those changes. In the meantime you can work around it by overriding `new/2` within your worker:
> 
> ```elixir
> def new(args, opts \\ []) when is_map(args) and is_list(opts) do
>   opts =
>     @opts
>     |> Keyword.merge(Application.get_env(:app, :thing, [max_attempts: 1]))
>     |> Keyword.merge(opts)
> 
>   Job.new(args, opts)
> end
> ```

`@opts` is unaccessible in this context. In order to work around this one'd need to replace the whole `Oban.Worker` with own implementation, which seems too hackish.
