### ISSUE TITLE
Oban fails to compile on Elixir 1.20-rc.4

### ISSUE THREAD

**Issue by Hermanverschooten** [sorentwo/oban#1445]
### Environment

- Oban Version 2.22.0
- Elixir & Erlang/OTP Versions (`elixir --version`) Elixir 1.20.0-rc.4 / Erlang 28.5

When triying to compile my project by doing `mix do clean + compile` it failed on `oban`, I retried but still failed:
```
MiniM4➜  multi_admin git:(main) ✗ mix deps.compile oban
==> oban
Compiling 65 files (.ex)
    error: module Oban.Repo is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module
    │
 10 │   require Oban.Repo
    │   ^
    │
    └─ lib/oban/stager.ex:10:3: Oban.Stager (module)

    error: module Oban.Repo is not loaded and could not be found. This may be happening because the module you are trying to load directly or indirectly depends on the current module
    │
 33 │   require Oban.Repo
    │   ^
    │
    └─ lib/oban/peers/database.ex:33:3: Oban.Peers.Database (module)


== Compilation error in file lib/oban/peers/database.ex ==
** (CompileError) lib/oban/peers/database.ex: cannot compile module Oban.Peers.Database (errors have been logged)

could not compile dependency :oban, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile oban --force", update it with "mix deps.update oban" or clean it with "mix deps.clean oban"

```

Herman

**Comment by sorenone** [comment]
This was already fixed on main (8a704aad7) and [reported upstream](https://github.com/elixir-lang/elixir/issues/15320). We'll have a patch release out today. 


Thanks for keeping us on our toes.
